# Generated by Django 5.1.5 on 2025-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Sex',
            field=models.SmallIntegerField(null=True),
        ),
    ]
