# Generated by Django 5.1.5 on 2025-02-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_email_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CreateTime',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UpdateTime',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='username',
        ),
    ]
