# Generated by Django 5.1.5 on 2025-03-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=1024)),
                ('username', models.CharField(max_length=100)),
                ('sex', models.SmallIntegerField(null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'water_detect_user',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pid', models.IntegerField(db_comment='父目录id', default=-1)),
                ('file_uid', models.CharField(db_comment='文件唯一标识', max_length=4096, null=True)),
                ('size', models.BigIntegerField(db_comment='文件大小', default=0)),
                ('file_path', models.CharField(db_comment='文件路径', default='', max_length=4096)),
                ('file_type', models.SmallIntegerField(db_comment='1:目录 2:图片 3:视频', default=0)),
                ('filename', models.CharField(db_comment='用户上传时的文件名', max_length=4096)),
                ('folder_type', models.SmallIntegerField(db_comment='0:普通文件夹 1:根文件夹 2:分析文件夹', default=0)),
                ('user_id', models.IntegerField(db_comment='userID')),
                ('thumbnail', models.BinaryField(db_comment='thumbnail', null=True)),
                ('extra', models.BinaryField(db_comment='extra', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'water_detect_file_info',
            },
        ),
    ]
