# Generated by Django 5.1.5 on 2025-02-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pid', models.IntegerField(db_comment='父目录id', default=-1)),
                ('size', models.BigIntegerField(db_comment='文件大小', default=0)),
                ('file_path', models.CharField(db_comment='文件路径', default='', max_length=4096)),
                ('folder_type', models.SmallIntegerField(db_comment='1:文件, 2:目录', default=0)),
                ('file_type', models.SmallIntegerField(db_comment='1:图片, 2:视频', default=0)),
                ('filename', models.CharField(db_comment='用户上传时的文件名', max_length=4096)),
                ('user_id', models.IntegerField(db_comment='userID')),
                ('thumbnail', models.BinaryField(db_comment='thumbnail', null=True)),
                ('extra', models.BinaryField(db_comment='extra', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
