# Generated by Django 5.1.5 on 2025-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='folder_type',
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_type',
            field=models.SmallIntegerField(db_comment='1:目录 2:图片 3:视频', default=0),
        ),
    ]
