# Generated by Django 5.1.5 on 2025-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_remove_fileinfo_folder_type_alter_fileinfo_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_uid',
            field=models.CharField(db_comment='文件唯一标识', max_length=4096, null=True),
        ),
    ]
