# Generated by Django 5.1.5 on 2025-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_fileinfo_file_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='folder_type',
            field=models.SmallIntegerField(db_comment='0:普通文件夹 1:根文件夹 2:分析文件夹', default=0),
        ),
    ]
