# Generated by Django 5.1.5 on 2025-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(verbose_name='文件ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('share_code', models.CharField(max_length=512, verbose_name='分享码')),
                ('valid_type', models.SmallIntegerField(blank=True, null=True, verbose_name='有效期类型')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('share_time', models.DateTimeField(blank=True, null=True, verbose_name='分享时间')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='提取码')),
                ('show_count', models.IntegerField(default=0, verbose_name='浏览次数')),
            ],
            options={
                'verbose_name': '分享信息',
                'verbose_name_plural': '分享信息',
                'db_table': 'water_detect_file_share',
                'indexes': [models.Index(fields=['file_id'], name='idx_file_id'), models.Index(fields=['user_id'], name='idx_user_id'), models.Index(fields=['share_time'], name='idx_share_time')],
            },
        ),
    ]
